# Generated by Django 3.0.2 on 2020-11-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'logistician'), (3, 'commercial'), (4, 'supervisor')], default=1),
            preserve_default=False,
        ),
    ]
