# Generated by Django 3.0.2 on 2021-01-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='abc_segmentation',
            field=models.CharField(blank=True, choices=[('A', 'Extremely important (A)'), ('B', 'Moderately important (B)'), ('C', 'Relatively unimportant (C)')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='fmr_segmentation',
            field=models.CharField(blank=True, choices=[('F', 'Frequently consumed (F)'), ('M', 'Moderately consumed (M)'), ('R', 'Rarely consumed (R)')], max_length=32, null=True),
        ),
    ]
