# Generated by Django 3.0.2 on 2021-01-15 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20210106_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='desired_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
