# Generated by Django 3.0.2 on 2020-08-28 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20200827_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='circuit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.Circuit'),
        ),
    ]
