# Generated by Django 3.0.2 on 2021-01-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_orderdetail_desired_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='shipping_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
