# Generated by Django 3.0.2 on 2020-08-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_order_circuit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference',
            field=models.CharField(max_length=200),
        ),
    ]
