# Generated by Django 3.0.2 on 2020-09-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20200828_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='available_trucks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='reception_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
