# Generated by Django 3.0.2 on 2021-01-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20210122_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
