# Generated by Django 3.0.2 on 2021-01-25 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_product_unit_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.Warehouse'),
        ),
    ]
