# Generated by Django 3.0.2 on 2021-01-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_customer_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
