# Generated by Django 3.0.2 on 2021-01-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_product_profit_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='monthly_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
