# Generated by Django 3.0.2 on 2021-01-22 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_product_unit_size'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcheck',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.Warehouse'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='status',
            field=models.CharField(choices=[('A', 'A'), ('Q', 'Q'), ('R', 'R')], default='A', max_length=32),
        ),
        migrations.AlterField(
            model_name='stockcheck',
            name='status',
            field=models.CharField(choices=[('A', 'A'), ('Q', 'Q'), ('R', 'R')], default='A', max_length=32),
        ),
    ]
