# Generated by Django 3.0.2 on 2021-01-25 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_orderdetail_desired_at'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcheck',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.Warehouse'),
        ),
    ]
