# Generated by Django 3.0.2 on 2021-01-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='edited_forecasted_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
