# Generated by Django 3.0.2 on 2020-12-01 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='version',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validated_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='version',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Pending', 'Pending'), ('Validated', 'Validated')], default='Created', max_length=32),
        ),
    ]
