# Generated by Django 3.0.2 on 2020-08-26 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockforecast',
            name='stockforecast_stock_sp_fd_uniq',
        ),
        migrations.RemoveField(
            model_name='stockforecast',
            name='stock',
        ),
        migrations.AddField(
            model_name='stockforecast',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.Product'),
        ),
        migrations.AddField(
            model_name='stockforecast',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.Warehouse'),
        ),
        migrations.AddConstraint(
            model_name='stockforecast',
            constraint=models.UniqueConstraint(fields=('product', 'warehouse', 'forecast_date', 'circuit', 'forecast_version'), name='stockforecast_stock_sp_fd_uniq'),
        ),
    ]
