# Generated by Django 3.0.2 on 2020-08-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0002_auto_20200826_1029'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockforecast',
            name='stockforecast_stock_sp_fd_uniq',
        ),
        migrations.AddConstraint(
            model_name='stockforecast',
            constraint=models.UniqueConstraint(fields=('product', 'warehouse', 'forecast_date', 'circuit', 'forecast_version'), name='unique_forecast'),
        ),
    ]
