# Generated by Django 3.0.2 on 2020-12-02 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0002_auto_20201201_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'permissions': (('request_review', 'Send review request'), ('validate_version', 'Validate a version'))},
        ),
    ]
