# Generated by Django 3.0.2 on 2020-12-02 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0003_auto_20201202_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='validated_by',
            new_name='approved_by',
        ),
    ]
