# Generated by Django 3.0.2 on 2021-01-13 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0004_target'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'permissions': (('can_request_review', 'Can send review request'), ('can_validate_version', 'Can validate a version'))},
        ),
    ]
