# Generated by Django 3.0.2 on 2021-01-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0005_auto_20210113_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='status',
            field=models.CharField(choices=[('Auto Generated', 'Auto Generated'), ('Confirmed', 'Confirmed'), ('Sent For Review', 'Sent For Review')], default='Auto Generated', max_length=32),
        ),
    ]
