# Generated by Django 3.0.2 on 2021-01-18 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20210106_1318'),
        ('forecasting', '0007_auto_20210114_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versiondetail',
            name='status',
            field=models.CharField(choices=[('Auto Generated', 'Auto Generated'), ('Confirmed', 'Confirmed'), ('Sent For Review', 'Sent For Review'), ('Approved', 'Approved')], default='Auto Generated', max_length=32),
        ),
        migrations.CreateModel(
            name='PlannedOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Active', 'Active'), ('Archived', 'Archived')], default='Created', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planned_at', models.DateField(blank=True, null=True)),
                ('planned_quantity', models.IntegerField(blank=True, null=True)),
                ('circuit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.Circuit')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.Customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
